import datetime, random, string
src = open('main.py', encoding='utf-8').read()
c = []
c.append('class GiftOrderRequest(BaseModel):')
c.append('    order_id: str')
c.append('class RedeemRequest(BaseModel):')
c.append('    code: str')
c.append('@app.post("/create-gift")')
c.append('async def create_gift(req: GiftOrderRequest, authorization: str = Header(None)):')
c.append('    user_id, sb = await verify_user(authorization)')
c.append('    try:')
c.append('        result = await capture_paypal_order(req.order_id)')
c.append('        if result["status"] != "COMPLETED": raise HTTPException(status_code=400, detail="Payment not completed.")')
c.append('        import random, string')
c.append('        chars = string.ascii_uppercase + string.digits')
c.append('        code = "SPIRAL-"+"".join(random.choices(chars,k=4))+"-"+"".join(random.choices(chars,k=4))')
c.append('        sb.table("gift_codes").insert({"code":code,"credits":500000,"amount_paid":5.00,"created_by":user_id}).execute()')
c.append('        return {"success":True,"code":code,"credits":500000}')
c.append('    except HTTPException: raise')
c.append('    except Exception as e: raise HTTPException(status_code=500,detail=f"Gift error: {str(e)}")')
